# Generated by Django 3.2.7 on 2021-12-10 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailstreamforms', '0002_form_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='error_title',
            field=models.CharField(default='Achtung! Bitte korrigieren Sie die Formfehler', help_text='An optional error title to show when the form has validation errors', max_length=64, null=True, verbose_name='Error Title'),
        ),
        migrations.AddField(
            model_name='form',
            name='success_title',
            field=models.CharField(default='Vielen Dank für Ihren Beitrag', help_text='An optional success title to show when the form has validation errors', max_length=64, null=True, verbose_name='Success Title'),
        ),
    ]
